### ISSUE TITLE
GET handlers do not respond to HEAD requests

### ISSUE THREAD

**Issue by gfredericks** [Prismatic/fnhouse#31]
I'm not an HTTP nerd, but I noticed that when rewriting my routes from compojure to fnhouse HEAD requests stopped working.

It looks like compojure automatically accepts HEAD in place of GET; I haven't looked in detail but I imagine it just runs the normal GET request and then removes the body.

Should fnhouse do something similar? At least in an opt-in sort of way?

**Comment by w01fe** [comment]
You can write explicit HEAD methods in fnhouse, and when we want the above behavior, we just include this middleware:

```clojure
(defn head-to-get-fallback-middleware [handler]
  (fn [req]
    (let [resp (handler req)]
      (if (and (= (:request-method req) :head) (#{404 405} (:status resp)))
        (let [get-resp (handler (assoc req :request-method :get))]
          (if (= 200 (:status get-resp))
            (assoc get-resp :body nil)
            resp))
        resp))))
```

It's a goal of fnhouse to pull apart handlers and routing.  I suppose one could argue that this should be part of routing, and I think we thought about that but decided to keep it simple and make this opt-in via middleware.   Especially since it could be unexpected and costly to have a method do all its work to compute a body and then throw it away.  

What do you think?

**Comment by gfredericks** [comment]
This sounds good to me, I can definitely relate to not wanting all the extra computation by default.

**Comment by w01fe** [comment]
Cool.  If you think it would be useful, we could add this middleware to fnhouse.middleware? PR welcome.
